/**
 * @file AttractionCheckinPage Component
 * @description Page for completing an attraction check-in task
 */

import { Button } from '@/components/common/Button'
import { Card } from '@/components/common/Card'
import { Modal } from '@/components/common/Modal'
import { useAttraction } from '@/hooks/useAttraction'
import { useWallet } from '@/hooks/useWallet'
import { useState, useEffect } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { ethers } from 'ethers'

/**
 * AttractionCheckinPage Component
 */
export function AttractionCheckinPage() {
    const { taskId } = useParams<{ taskId: string }>()
    const navigate = useNavigate()
    const { isConnected, address, connect } = useWallet()
    const { getTask, getContract, getUserTaskInfo } = useAttraction()

    const [task, setTask] = useState<any>(null)
    const [loading, setLoading] = useState(false)
    const [verifying, setVerifying] = useState(false)
    const [location, setLocation] = useState<{ lat: number; lng: number } | null>(null)
    const [distance, setDistance] = useState<number | null>(null)
    const [showSuccessModal, setShowSuccessModal] = useState(false)

    // Load task details
    useEffect(() => {
        const loadData = async () => {
            if (!taskId) return
            const taskData = await getTask(taskId)
            setTask(taskData)

            // Check if already completed
            if (address) {
                const info = await getUserTaskInfo(taskId, address)
                if (info?.completed) {
                    alert('You have already completed this task!')
                    navigate('/attractions')
                }
            }
        }
        loadData()
    }, [taskId, getTask, getUserTaskInfo, address, navigate])

    const handleGetLocation = () => {
        setVerifying(true)
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(
                (position) => {
                    const userLat = position.coords.latitude
                    const userLng = position.coords.longitude
                    setLocation({ lat: userLat, lng: userLng })

                    if (task) {
                        // Calculate distance (simple Haversine or approximation)
                        // For MVP, simplistic distance calculation
                        const R = 6371e3; // metres
                        const φ1 = userLat * Math.PI / 180;
                        const φ2 = task.location.lat * Math.PI / 180;
                        const Δφ = (task.location.lat - userLat) * Math.PI / 180;
                        const Δλ = (task.location.lng - userLng) * Math.PI / 180;

                        const a = Math.sin(Δφ / 2) * Math.sin(Δφ / 2) +
                            Math.cos(φ1) * Math.cos(φ2) *
                            Math.sin(Δλ / 2) * Math.sin(Δλ / 2);
                        const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
                        const d = R * c; // in metres

                        setDistance(d)
                    }
                    setVerifying(false)
                },
                (error) => {
                    alert(`获取位置失败: ${error.message}`)
                    setVerifying(false)
                }
            )
        } else {
            alert('浏览器不支持地理位置')
            setVerifying(false)
        }
    }

    const handleCheckin = async () => {
        if (!isConnected) {
            await connect()
            return
        }

        if (!location) {
            alert('请先获取位置验证')
            return
        }

        /* 
        NOTE: In a real production app, the signature MUST be generated by a secure backend service.
        The backend would verify the GPS coordinates and then sign the data.
        For this purely frontend demo/test, we are simulating the backend using the Owner's private key.
        WARNING: NEVER EXPOSE PRIVATE KEYS IN PRODUCTION FRONTEND CODE.
        */
        const TEST_SIGNER_PRIVATE_KEY = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80" // Hardhat Account #0

        setLoading(true)
        try {
            const contract = await getContract()
            if (!contract) throw new Error("Contract not available")

            // 1. Prepare data
            const contentHash = ethers.keccak256(ethers.toUtf8Bytes("FrontendCheckin"))
            const latInt = Math.round(location.lat * 1000000)
            const lngInt = Math.round(location.lng * 1000000)
            const expiry = Math.floor(Date.now() / 1000) + 300 // 5 mins expiry

            // 2. Generate Signature (Simulating Backend)
            const wallet = new ethers.Wallet(TEST_SIGNER_PRIVATE_KEY)

            // abi.encodePacked(taskId, msg.sender, contentHash, latitude, longitude, expiry)
            const messageHash = ethers.solidityPackedKeccak256(
                ['uint256', 'address', 'bytes32', 'int256', 'int256', 'uint256'],
                [taskId, address, contentHash, latInt, lngInt, expiry]
            )
            const messageBytes = ethers.getBytes(messageHash)
            const signature = await wallet.signMessage(messageBytes)

            console.log("Generated Signature:", signature)

            // 3. Call Contract completeTask
            const tx = await contract.completeTask(
                taskId,
                contentHash,
                latInt,
                lngInt,
                expiry,
                signature
            )

            console.log("Check-in Tx:", tx.hash)
            await tx.wait()

            // alert("打卡成功！奖励已发放！") 
            // Replace alert with modal
            setShowSuccessModal(true)

        } catch (error) {
            console.error("Check-in failed:", error)
            const msg = error instanceof Error ? error.message : "Unknown error"
            alert(`打卡失败: ${msg}`) // Keep error alert for now or replace? User asked for Success modal specifically.
        } finally {
            setLoading(false)
        }
    }

    if (!task) return <div className="text-center p-10 text-white">Loading task...</div>

    return (
        <div className="max-w-md mx-auto space-y-6">
            <div>
                <h1 className="text-3xl font-bold text-white mb-2">景点打卡</h1>
                <p className="text-text-muted">验证您的位置以完成任务</p>
            </div>

            <Card>
                <div className="relative h-48 -m-4 mb-4 overflow-hidden rounded-t-lg">
                    <img src={task.coverImage} alt={task.name} className="w-full h-full object-cover" />
                    <div className="absolute inset-0 bg-gradient-to-t from-background-dark/80 to-transparent" />
                    <div className="absolute bottom-4 left-4">
                        <h2 className="text-xl font-bold text-white">{task.name}</h2>
                        <p className="text-sm text-gray-300">{task.location.name}</p>
                    </div>
                </div>

                <Card.Body className="space-y-6">
                    {/* Location Verification */}
                    <div className="bg-primary-900/20 p-4 rounded-lg border border-primary-500/30">
                        <div className="flex justify-between items-center mb-2">
                            <span className="text-gray-300">当前位置</span>
                            {location && (
                                <span className="text-xs text-primary font-mono">
                                    {location.lat.toFixed(6)}, {location.lng.toFixed(6)}
                                </span>
                            )}
                        </div>

                        {!location ? (
                            <Button
                                variant="outline"
                                fullWidth
                                onClick={handleGetLocation}
                                loading={verifying}
                            >
                                📍 获取并验证位置
                            </Button>
                        ) : (
                            <div className="text-center space-y-2">
                                <div className={`text-lg font-bold ${distance !== null && distance <= task.location.radius ? 'text-green-500' : 'text-red-500'}`}>
                                    {distance !== null ? `距离目标 ${Math.round(distance)} 米` : '计算中...'}
                                </div>
                                <p className="text-xs text-gray-400">打卡范围: {task.location.radius} 米</p>

                                <Button
                                    variant="outline"
                                    size="sm"
                                    onClick={handleGetLocation}
                                    loading={verifying}
                                >
                                    🔄 重新定位
                                </Button>
                            </div>
                        )}
                    </div>

                    {/* Check-in Button */}
                    <Button
                        variant="primary"
                        fullWidth
                        size="lg"
                        disabled={!location || loading || (distance !== null && distance > task.location.radius)}
                        loading={loading}
                        onClick={handleCheckin}
                    >
                        {loading ? '正在打卡...' : '确认打卡'}
                    </Button>

                    {distance !== null && distance > task.location.radius && (
                        <p className="text-center text-xs text-red-400">
                            您不在打卡范围内，请移动到目标位置附近。
                        </p>
                    )}
                </Card.Body>
            </Card>

            {/* Success Modal */}
            <Modal
                isOpen={showSuccessModal}
                onClose={() => {
                    setShowSuccessModal(false)
                    navigate('/attractions') // Or stay? Usually navigate out.
                }}
                title="🏆 打卡成功"
                size="sm"
            >
                <div className="text-center space-y-6 py-4">
                    <div className="text-6xl animate-bounce">
                        🎉
                    </div>

                    <div className="space-y-2">
                        <h3 className="text-xl font-bold text-white">恭喜您完成任务！</h3>
                        <p className="text-text-muted">奖励已自动发送到您的钱包</p>
                    </div>

                    <div className="bg-primary-900/30 border border-primary-500/50 rounded-xl p-4">
                        <p className="text-sm text-text-muted mb-1">获得奖励</p>
                        <p className="text-3xl font-bold text-primary">
                            {task.rewardAmount} <span className="text-lg">MON</span>
                        </p>
                    </div>

                    <div className="pt-2">
                        <Button
                            variant="primary"
                            fullWidth
                            onClick={() => navigate('/rewards')}
                        >
                            查看我的奖励
                        </Button>
                        <button
                            className="mt-4 text-sm text-text-muted hover:text-white underline"
                            onClick={() => navigate('/attractions')}
                        >
                            返回任务列表
                        </button>
                    </div>
                </div>
            </Modal>
        </div>
    )
}
